export enum MainStatusEnum {
    AWAIT_DETECT = 'MS00',
    WRONG_URL = 'MS01',
    NO_FOCUS_PLACE_INFO = 'MS02',
    NOT_REVIEW_SECTION = 'MS03',
    READY_TO_START = 'MS04',
    LOADING = 'MS05',
    FAIL_LOAD = 'MS06',
    DONE_LOADING = 'MS07',
    ANALYZING = 'MS08',
    DONE_ANALYZE = 'MS09',
    FAIL_ANALYZE = 'MS10',
    ERROR = 'MS11'
}