export enum MainButtonTextEnum {
    START_DETECT = 'START_DETECT',
    RE_DETECT = 'RE_DETECT',
    START_LOAD = 'START_LOAD',
    RE_LOAD = 'RE_LOAD',
    STOP_LOAD = 'STOP_LOAD',
    START_ANALYZE = 'START_ANALYZE',
    STOP_ANALYZE = 'STOP_ANALYZE',
    OPEN_POPUP = 'OPEN_POPUP',
    RE_ANALYZE = 'RE_ANALYZE'
}
