export enum MainStatusEnum {
  AWAIT_DETECT = 'MS00',
  WRONG_URL = 'MS01',
  NO_FOCUS_PLACE_INFO = 'MS02',
  NOT_COMMENT_SECTION = 'MS03',
  READY_TO_START = 'MS04',
  SCROLLING = 'MS05',
  PAUSE_WRONG_URL = 'MS06',
  PAUSE_NO_FOCUS_PLACE_INFO = 'MS07',
  PAUSE_NOT_COMMENT_SECTION = 'MS08',
  DONE_SCROLLING = 'MS09'
}