export enum MainStatusEnum {
  AWAIT_DETECT = 'MS00',
  WRONG_URL = 'MS01',
  NOT_COMMENT_SECTION = 'MS02',
  READY_TO_START = 'MS03',
  SCROLLING = 'MS04',
  PAUSE_WRONG_URL = 'MS05',
  PAUSE_NOT_COMMENT_SECTION = 'MS06',
  DONE_SCROLLING = 'MS07'
}