export enum googlePlaceHtmlElement {
  PLACE_SECTION_TAB = '.hh2c6',
  PLACE_REVIEW_SECTION_SHOW_STAR_RATING = '.YTkVxc',
  PLACE_SINGLE_REVIEW = '.jftiEf',
  PLACE_SINGLE_REVIEW_STAR_RATING = '.kvMYJc',
  PLACE_SINGLE_REVIEW_RELATIVE_TIME = '.rsqaWe',
  PLACE_SINGLE_REVIEW_CONTENT_PART = '.MyEned',
  PLACE_SINGLE_REVIEW_CONTENT = '.wiI7pd',
  PLACE_SINGLE_REVIEW_REPLY_PART = '.CDe7pd',
  PLACE_SINGLE_REVIEW_REPLY_CONTENT = '.wiI7pd',
  PLACE_SINGLE_REVIEW_LIKE_COUNT = '.GBkF3d',
  PLACE_SINGLE_REVIEW_PHOTO_PART = '.KtCyie',
  PLACE_SINGLE_REVIEW_PHOTO_ELEMENTS = '.Tya61d'
}